#define ADAPTER_BUTTON_1  11
#define ADAPTER_BUTTON_2  12
#define ADAPTER_RGB_COUNT 4
#define ADAPTER_PORT_COUNT 4

#define ADAPTER_MANUFACTURER "HHL"
#define ADAPTER_PRODUCT "GC Pocket+"
#define ADAPTER_STRING "GCP+"

#define ADAPTER_FIRMWARE_VERSION 0x0007
#define ADAPTER_SETTINGS_VERSION 0x0003
#define ADAPTER_WEBUSB_URL "handheldlegend.github.io/gcp"